blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostList.as_view(), name="blog"),
    path('<slug:slug>', views.PostDetail.as_view(), name="post")
]

mazcomunicacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('web.urls', namespace="web")),
    path('', include('periodicos.urls', namespace="periodicos")),
    path('blog/', include('blog.urls', namespace='blog'))
]

web/urls.py
from django.urls import path, include

from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('servicios/<slug:slug>/', include([
        path('', views.servicio, name="servicios"),
        path('<slug:subslug>/', views.subservicio, name="servicio")
    ])),
    path('contacto/', views.contact, name="contacto"),
    path('politica-de-privacidad/', views.politica_privacidad, name="privacy-policy"),
    path('politica-de-cookies/', views.politica_cookies, name="cookie-policy")
]

blog/models.py
from django.db import models

import storage_backends


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    featured_image = models.ImageField(storage=storage_backends.PublicMediaStorage(), null=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic

from .models import Post


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'
    paginate_by = 5


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

blog/templates/blog.html
{% extends 'base.html' %}

{% block content %}
<section id="blog">
    <div class="container text-center">
        <h1>Blog</h1>
    </div>
    <div class="separator"></div>
    <div class="container">
        <div class="row justify-content-center">
            {% for post in post_list %}
            <div class="col-xl-3 col-lg-4 col-md-5 col-sm-6 col-xs-6 mx-4 mx-md-0 py-1 py-md-0">
                <div class="card text-center">
                    <img
                    class="card-img-top"
                    src="{{ post.featured_image.url }}"
                    alt=""
                    width="100%"
                    />
                    <div class="card-block">
                    <h4 class="card-title">{{ post.title }}</h4>
                    <a class="btn btn-default" href="{% url 'blog:post' post.slug %}">Leer más</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="container" >

      <div class="small-wrapper">
        <div class="text-center">
          <h1 class="post-title">{{ object.title }}</h1>
          <div class="separator"></div>
          <br />
          <img
            class="img-fluid"
            src="{{ object.featured_image.url }}"
            alt=""
          />
        </div>
        <hr />
        <!--        <span class="post-date">18 Jan 2018</span>-->
        <div class="container" id="post-content">
            {{ object.content | safe }}
        </div>

        <hr />
      </div>
    </div>
    <!-- /.container -->
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e34f8bcd3c5b38b"></script>
<script>
$(function() {
  $("#post-content img").each(function(){
      $(this).addClass("img-fluid")
  })
  $("iframe").each(function(){
    $(this).css("max-width", "100%")
  })
})
</script>
{% endblock %}