blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostList.as_view(), name="blog"),
    path('<slug:slug>', views.PostDetail.as_view(), name="post")
]

mazcomunicacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('web.urls', namespace="web")),
    path('', include('periodicos.urls', namespace="periodicos")),
    path('blog/', include('blog.urls', namespace='blog'))
]

periodicos/urls.py
from django.urls import path, include

from . import views

app_name = "periodicos"

urlpatterns = [
    path('portadas-y-columnas/', include([
        path('coahuila/', views.portadas_list, name="portadas"),
        path('coahuila/<slug:slug>/', views.portada, name="portada"),
        path('mexico/', views.portadas_list_mexico, name="portadas_mexico"),
        path('mexico/<slug:slug>/', views.portada_mexico, name="portada_mexico"),
        path('nuevo-leon/', views.portadas_list_nl, name="portadas_nl"),
        path('nuevo-leon/<slug:slug>', views.portada_nl, name="portada_nl"),
    ]))
]

web/urls.py
from django.urls import path, include

from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('servicios/<slug:slug>/', include([
        path('', views.servicio, name="servicios"),
        path('<slug:subslug>/', views.subservicio, name="servicio")
    ])),
    path('contacto/', views.contact, name="contacto"),
    path('politica-de-privacidad/', views.politica_privacidad, name="privacy-policy"),
    path('politica-de-cookies/', views.politica_cookies, name="cookie-policy")
]

web/templates/partials/footer.html
{% load static %}
{% load nav_items %}

<footer id="myFooter">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <img
            src="{% static 'assets/logo-sm.png' %}"
            alt=""
            style="width: 100px; height: auto; padding-top: 30px"
          />
        </div>
        <div class="col-sm-4">
          <hr>
          <ul>
            <li><h6>Álvaro Obregón 974 – 1 Centro.</h6></li>
            <li>Saltillo, Coahuila</li>
            <li>(844) 881 9829</li>
            <li>(844) 138 2427</li>
            <li>director@mazcomunicacion.com.mx</li>
          </ul>
        </div>
        <div class="col-sm-1">
          <ul>
            <h5></h5>
            <li><a href="{% url 'web:index' %}">Inicio</a></li>
            <li><a href="{% url 'blog:blog' %}">Blog</a></li>
            <li><a href="{% service_url %}">Servicios</a></li>
            <li><a href="{% url 'web:contacto' %}">Contacto</a></li>
          </ul>
        </div>
        <div class="col-sm-2">
          <h5></h5>
          <ul>
            <li><a href="{% url 'web:privacy-policy' %}">Política de privacidad</a></li>
            <li><a href="{% url 'web:cookie-policy' %}">Política de cookies</a></li>
          </ul>
        </div>
        <div class="col-sm-3" style="padding-top: 30px">
          <div class="social-networks">
            <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fab fa-facebook"></i></a>
            <a href="#" class="google"><i class="fab fa-google-plus"></i></a>
          </div>
          <a href="{% url 'web:contacto' %}"><button type="button" class="btn btn-default">Contacto</button></a>
        </div>
      </div>
    </div>
    <div class="footer-copyright text-center">
      <p>© {% now "Y" %} MAZ Comunicación</p>
    </div>
</footer>

web/templates/partials/nav.html
{% load static %}
{% load nav_items %}

<nav class="navbar navbar-expand-sm navbar-light bg-light sticky-top">
    <a href="{% url 'web:index' %}">
        <img
          src="{% static 'assets/logo.png' %}"
          height="55rem"
          width="auto"
          alt=""
          class="d-none d-sm-block"
        />
        <img
          src="{% static 'assets/logo-sm.png' %}"
          height="55rem"
          width="auto"
          alt=""
          class="d-sm-none"
        />
    </a>

  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarResponsive"
    aria-controls="navbarResponsive"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item">
        <a href="/" class="nav-link">Inicio</a>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdownMenuLink"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Servicios
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            {% get_services_list as services %}

            {% for service in services %}
            <a class="dropdown-item" href="{% url 'web:servicios' service.slug %}">{{ service.title }}</a>
            {% endfor %}

            <a class="dropdown-item" href="{% url 'periodicos:portadas' %}">Portadas Coahuila</a>
            <a class="dropdown-item" href="{% url 'periodicos:portadas_mexico' %}">Portadas México</a>
            <a class="dropdown-item" href="{% url 'periodicos:portadas_nl' %}">Portadas Nuevo León</a>
        </div>
      </li>
      <li class="nav-item">
        <a href="{% url 'blog:blog' %}" class="nav-link">Blog</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'web:contacto' %}" class="nav-link">Contacto</a>
      </li>
    </ul>
  </div>
</nav>