blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostList.as_view(), name="blog"),
    path('<slug:slug>', views.PostDetail.as_view(), name="post")
]

mazcomunicacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('web.urls', namespace="web")),
    path('', include('periodicos.urls', namespace="periodicos")),
    path('blog/', include('blog.urls', namespace='blog'))
]

periodicos/urls.py
from django.urls import path, include

from . import views

app_name = "periodicos"

urlpatterns = [
    path('portadas-y-columnas/', include([
        path('coahuila/', views.portadas_list, name="portadas"),
        path('coahuila/<slug:slug>/', views.portada, name="portada"),
        path('mexico/', views.portadas_list_mexico, name="portadas_mexico"),
        path('mexico/<slug:slug>/', views.portada_mexico, name="portada_mexico"),
        path('nuevo-leon/', views.portadas_list_nl, name="portadas_nl"),
        path('nuevo-leon/<slug:slug>', views.portada_nl, name="portada_nl"),
    ]))
]

web/urls.py
from django.urls import path, include

from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('servicios/<slug:slug>/', include([
        path('', views.servicio, name="servicios"),
        path('<slug:subslug>/', views.subservicio, name="servicio")
    ])),
    path('contacto/', views.contact, name="contacto"),
    path('politica-de-privacidad/', views.politica_privacidad, name="privacy-policy"),
    path('politica-de-cookies/', views.politica_cookies, name="cookie-policy")
]

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    city = models.CharField(max_length=50)
    sub_coah = models.BooleanField()
    sub_nl = models.BooleanField()
    sub_mex = models.BooleanField()
    message = models.TextField()

web/models.py
from django.db import models
import storage_backends


class Servicio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(storage=storage_backends.PublicMediaStorage(), blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class SubServicio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField(storage=storage_backends.PublicMediaStorage())
    parent = models.ForeignKey(Servicio, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

web/templates/base.html
{% load static %}
{% load analytical %}

<!DOCTYPE html>
<head>
    {% analytical_head_top %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.css">
    <link href="https://mazcomunicacion.s3-us-west-1.amazonaws.com/fonts/fonts.css" rel="stylesheet">
    {% block style %}{% endblock %}
    <style>
        body {
            font-family: Gotham;
        }
        h1, h2 {
            font-family: Gobold !important;
        }
    </style>
    {% analytical_head_bottom %}
</head>
<body>
    {% analytical_body_top %}
    {% include 'partials/nav.html' %}

    <div style="min-height: 70vh;">
        {% block content%}
        {% endblock %}
    </div>

    {% include 'partials/footer.html'%}

    <div class="alert text-center cookiealert" role="alert">
        Usamos cookies para mejorar tu experiencia. Al seguir navegando por nuestro sitio aceptas nuestra <a href="{% url 'web:cookie-policy' %}" >politíca de cookies.</a>

        <button type="button" class="btn btn-primary btn-sm acceptcookies" aria-label="Close">
            Aceptar
        </button>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.js"></script>
    {% block scripts %}{% endblock %}
    {% analytical_body_bottom %}
</body>
</html>

web/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="container text-center">
  <h1>Contacto</h1>
</div>
<div class="separator"></div>
<br />
<div class="container text-center">
  <h2>¡Hola!</h2>
  <h3>¿Cómo te podemos ayudar?</h3>
</div>
<div class="container" style="padding: 20px 0">
        {% if sucess %}
            <div class="alert alert-success" role="alert">
                Gracias por contactarnos.
            </div>
        {% endif %}
        {% if errors %}
            <div class="alert alert-danger" role="alert">
                Por favor verifique todos los campos.
            </div>
        {% endif %}
      <form id="contact-form" method="post" role="form">
        {% csrf_token %}
        <div class="messages"></div>

        <div class="controls">
          <div class="row">
            <div class="col-md-6">
              {{ form.name | as_crispy_field }}
            </div>
            <div class="col-md-6">
              {{ form.email | as_crispy_field }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              {{ form.phone | as_crispy_field }}
            </div>
            <div class="col-md-6">
              {{ form.city | as_crispy_field }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {{ form.message | as_crispy_field }}
            </div>
            <div class="col-md-12">
                {{ form.sub_coahuila | as_crispy_field }}
                {{ form.sub_nl | as_crispy_field }}
                {{ form.sub_mexico | as_crispy_field }}
            </div>
            <div class="col-md-12">
              <input
                type="submit"
                class="btn btn-default btn-send"
                value="Enviar mensaje"
              />
            </div>
          </div>
        </div>
      </form>
    </div>
    <br />
</div>
{% endblock %}

web/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
.jumbotron {
  color: white;
  background-image: url("{{ banner.image.url }}");
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  height: 60vh;
}
</style>

{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid d-flex">
  <div class="container text-center align-self-center">
    <h1 class="text-white"><span style="color: #dcbe00;">MAZ</span> Comunicación</h1>
    <h3 class="text-white">{{ banner.sub_header }}</h3>
  </div>
</div>
<section>
    <div class="container text-center">
        <h1>Acerca de MAZ</h1>
        <div class="separator"></div>
        <h5>{{ about.description | safe}}</h5>
    </div>

    <div class="container-fluid text-center mt-5">
        <img src="{{ about.banner.url }}" alt="" class="img-fluid">
    </div>

    <section class="hk-services" id="servicios">
        <div class="container">
            <div class="row">
            <div class="col">
                <div class="hk-services-header text-center">
                <h2>
                    Servicios
                </h2>
                </div>
            </div>
            </div>
            <div class="separator"></div>
            <div class="row">
            {% for service in services %}
                <div class="col-sm-6 col-md-4" style="background-image: url({{ service.image.url }});background-size: cover;">
                    <a href="{% url 'web:servicios' service.slug %}">
                    <div class="hk-services-box text-center">
                        <!-- <h3>{{ service.title }}</h3> -->
                    </div>
                    </a>
                </div>
            {% endfor %}
                <div class="col-sm-6 col-md-4" style="background-image: url({{ periodicos.coahuila.image.url }});background-size: cover;">
                    <a href="{% url 'periodicos:portadas' %}">
                    <div class="hk-services-box text-center">
                        <!-- <h3>Portadas Coahuila</h3> -->
                    </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-4" style="background-image: url({{ periodicos.mexico.image.url }});background-size: cover;">
                    <a href="{% url 'periodicos:portadas_mexico' %}">
                    <div class="hk-services-box text-center">
                        <!-- <i class="fas fa-paint-brush"></i>
                        <h3>Portadas México</h3> -->
                    </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-4" style="background-image: url({{ periodicos.nl.image.url }});background-size: cover;">
                    <a href="{% url 'periodicos:portadas_nl' %}">
                    <div class="hk-services-box text-center">
                        <!-- <i class="fas fa-paint-brush"></i>
                        <h3>Portadas Nuevo León</h3> -->
                    </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section id="blog">
        <div class="container text-center">
            <h1>Blog</h1>
        </div>
        <div class="separator"></div>
        <div class="container">
            <div class="container">
                <div class="row">
                    {% for post in post_list %}
                    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                        <div class="card text-center">
                            <img
                            class="card-img-top"
                            src="{{ post.featured_image.url }}"
                            alt=""
                            width="100%"
                            />
                            <div class="card-block">
                            <h4 class="card-title">{{ post.title }}</h4>
                            <a class="btn btn-default" href="{% url 'blog:post' post.slug %}">Leer más</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <div class="container text-center">
        <a href="{% url 'blog:blog' %}" class="btn btn-default">Todas las entradas</a>
    </div>
</section>
{% endblock content %}

{% block scripts %}

{% endblock %}

web/templates/politica-cookies.html
{% extends 'base.html' %}

{% block content %}
<div class="small-wrapper">
    <div class="text-center">
      <h1 class="post-title">Política de Cookies</h1>
      <div class="separator"></div>
      <br />
    </div>

    <div class="container">
      <p>
        Nuestro sitio de internet utiliza cookies, por lo cual, el visitante
        admite que al navegar en ella dejará ese rastro que nos permitirá
        conocer la manera como ha interactuado con nuestro canal y éste le
        reconocerá cuando regrese. El uso de esta herramienta tiene el propósito
        de mejorar la experiencia del usuario en sus visitas a nuestro sitio.
      </p>

      <p>
        Nuestra página también usa herramientas para conocer datos de uso de los
        visitantes que nos permiten conocer sus preferencias o comportamiento,
        lo cual es útil para el perfeccionamiento de nuestra página y para la
        toma de decisiones dentro de nuestra estrategia de comunicación.
      </p>
    </div>
</div>
{% endblock %}

web/templates/politica-privacidad.html
{% extends 'base.html' %}

{% block content %}
<div class="small-wrapper">
    <div class="text-center">
      <h1 class="post-title">Política de Privacidad</h1>
      <div class="separator"></div>
      <br />
    </div>

    <div class="container">
      <p>
        MAZ Comunicación y Estrategia SC desea servirte para que consigas los
        objetivos de tu empresa u organización. Para ello, necesitamos
        información. La política de privacidad garantiza que:
      </p>
      <ol>
        <li>
          La obtención de sólo la información suficiente para cumplir nuestra
          misión.
        </li>
        <li>
          El uso exclusivo de la información para los fines por los cuales fue
          obtenida
        </li>
        <li>
          No se comparte la información a personas internas ni externas no
          involucradas en nuestros procesos vinculados a tu caso.
        </li>
        <li>
          Sólo se copia o transfiere a nuestros sistemas aquella información que
          debemos administrar.
        </li>
        <li>
          Las personas implicadas en el conocimiento y uso de la información,
          son profesionales conocedores de la ley y la importancia de la
          privacidad de los datos.
        </li>
      </ol>
      <p>
        Para poder ofrecer nuestros servicios, necesitaremos dos tipos de datos:
      </p>
      <ol>
        <li>Los datos de identidad de nuestros clientes</li>
        <li>Los datos relacionados con su situación o asunto a tratar.</li>
      </ol>
      <p>
        En el primero de los casos siempre necesitaremos el nombre de personas y
        por lo menos un correo electrónico. De forma adicional, podremos
        solicitar otra información como celular de trabajo, domicilio de la
        empresa, domicilio de internet, perfiles de redes sociales y cualquier
        otro que nos permita establecer comunicación con la o las personas
        indicadas para trabajar. En ningún caso solicitaremos información de
        identidad que no necesitemos para comunicarnos. MAZ Comunicación y
        Estrategia SC rechaza toda práctica de asedio o acoso con información
        que nuestros clientes o seguidores no desean. Pensamos que el spam no
        sólo es ilegal, sino también falto de ética y por supuesto, muy molesto.
        Toda comunicación nace y se desarrolla como parte de un acuerdo mutuo de
        sostener intercambios de ideas y mensajes útiles para el cumplimiento de
        nuestros objetivos.
      </p>
      <p>
        En el segundo caso, impera la misma política de obtener sólo lo que es
        estrictamente necesario y para los fines que se hayan planteado, de
        conformidad con cada situación. Se debe advertir, sin embargo, que para
        el pleno conocimiento de una situación y el desarrollo de programas,
        acciones, estrategias, planes y demás que pudiéramos ofrecer, será
        necesario obtener información que puede llegar a ser delicada en la
        organización y amerite un alto grado de responsabilidad en su manejo.
        Nos referimos a casos como conocimiento de ventas, contraseñas,
        contratos, nóminas y otras que, por su condición durante el servicio que
        prestamos, formen parte de la información que podremos requerir.
      </p>
      <p>
        MAZ Comunicación y Estrategia SC tiene la política de clasificar la
        información por su condición de privacidad o publicidad y acordar con el
        cliente la manera como se habrá de manejar cada una de ellas de
        conformidad con su caso. Nuestros colaboradores asumen la
        responsabilidad de atender todas las cláusulas de privacidad que se
        ameriten en los contratos de prestación de servicios.
      </p>
      <p>
        El principio de suficiencia nos impone la obligación de conocer sólo lo
        necesario e impide obtener información que pueda permanecer ociosa en
        nuestras manos; además, impide que cualquier información, incluso útil,
        sea trasladada o copiada a nuestros equipos de cómputo o memorias.
        Accederemos a la información siempre que se necesite y la mantendremos
        bajo el dominio pleno y exclusivo de nuestros clientes, a menos que sea
        indispensable trasladarla a nuestros equipos.
      </p>
      <p>
        Ninguna información relativa a los asuntos de nuestros clientes
        permanece sólo bajo nuestra custodia o administración, salvo que sea
        aquella que forma parte de los procesos propios de trabajo, por lo que
        estará sólo bajo dominio nuestro de forma transitoria. En este sentido,
        nosotros sólo conservamos copias de la información, cualquiera que sea
        su formato o medio de resguardo.
      </p>
      <p>
        La información de terceras personas bajo nuestra administración y
        resguardo, se obtiene a partir del consentimiento de su propietario, de
        conformidad con procedimientos y acordados entre el propietario de la
        información y MAZ Comunicación y Estrategia SC y con el uso de
        herramientas que mutuamente consideramos seguras.
      </p>
      <p>
        MAZ Comunicación y Estrategia SC está sujeto a las leyes en materia de
        protección a la privacidad y datos personales.
      </p>
    </div>
</div>
{% endblock %}

web/templates/services.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="container text-center">
          <h1>{{ service.title }}</h1>
          <div class="separator"></div>
          <h4>{{ service.description }}</h4>
        </div>

        <section>
            <div class="container">
              <div class="row justify-content-center">

                  {% for subservice in service.subservicio_set.all %}
                      <div class="col-9 col-xl-3 col-lg-4 col-md-5 col-sm-6 mx-4 mx-md-0 py-1 py-md-0">
                          <div class="card">
                              <img src="{{subservice.image.url}}" class="card-img-top" alt="">
                              <div class="card-body">
                                <h5 class="card-title">{{ subservice.title }}</h5>
                                <a href="{% url 'web:servicio' service.slug subservice.slug %}" class="btn btn-default stretched-link">Ver</a>
                              </div>
                          </div>
                      </div>

                  {% endfor %}

              </div>
            </div>
        </section>
      </section>
{% endblock content %}

web/templates/subservicio.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid pt-2">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'web:servicios' parent.slug %}" class="text-primary">{{ parent.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ service.title }}</li>
      </ol>
    </nav>
</div>
<div class="container pt-3">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ service.image.url }}" alt="" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h1>{{ service.title }}</h1>
            <p class="lead">{{ service.description }}</p>
        </div>
    </div>
</div>
<div class="container text-center pb-4 pt-2">
    <a href="{% url 'web:contacto' %}"><button class="btn btn-default">Cotizar</button></a>
</div>
{% endblock %}