mazcomunicacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('web.urls', namespace="web")),
    path('', include('periodicos.urls', namespace="periodicos")),
    path('blog/', include('blog.urls', namespace='blog'))
]

periodicos/urls.py
from django.urls import path, include

from . import views

app_name = "periodicos"

urlpatterns = [
    path('portadas-y-columnas/', include([
        path('coahuila/', views.portadas_list, name="portadas"),
        path('coahuila/<slug:slug>/', views.portada, name="portada"),
        path('mexico/', views.portadas_list_mexico, name="portadas_mexico"),
        path('mexico/<slug:slug>/', views.portada_mexico, name="portada_mexico"),
        path('nuevo-leon/', views.portadas_list_nl, name="portadas_nl"),
        path('nuevo-leon/<slug:slug>', views.portada_nl, name="portada_nl"),
    ]))
]

web/urls.py
from django.urls import path, include

from . import views

app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('servicios/<slug:slug>/', include([
        path('', views.servicio, name="servicios"),
        path('<slug:subslug>/', views.subservicio, name="servicio")
    ])),
    path('contacto/', views.contact, name="contacto"),
    path('politica-de-privacidad/', views.politica_privacidad, name="privacy-policy"),
    path('politica-de-cookies/', views.politica_cookies, name="cookie-policy")
]

periodicos/models.py
from django.db import models
import storage_backends

PORTADAS = 1
PORTADASMEXICO = 2
PORTADASNL = 3
CATEGORY = (
    (PORTADAS, ('Portadas Coahuila')),
    (PORTADASMEXICO, ('Portadas México')),
    (PORTADASNL, ('Portadas Nuevo León'))
)


class PortadasYColumnas(models.Model):

    title = models.CharField(max_length=15)
    thumbnail = models.ImageField(storage=storage_backends.PublicMediaStorage(), blank=True)
    file = models.FileField(storage=storage_backends.NewsMediaStorage())
    slug = models.SlugField(blank=True)
    category = models.PositiveSmallIntegerField(
        choices=CATEGORY,
        default=PORTADAS
    )

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = "Portadas y Columnas"


class Configuracion(models.Model):
    title = models.PositiveSmallIntegerField(
        choices=CATEGORY,
        default=PORTADAS
    )
    image = models.ImageField(storage=storage_backends.PublicMediaStorage(), blank=True)

    def __str__(self):
        # return str(CATEGORY[self.title.imag][1])
        return list(filter(lambda category: category[0] == self.title, CATEGORY))[0][1]

    class Meta:
        verbose_name_plural = "Configuraciones"

periodicos/views.py
from django.shortcuts import render, get_object_or_404

from .models import PortadasYColumnas


def portadas_list(request):
    objs = PortadasYColumnas.objects.filter(category=1)
    context = {
        'title': "Portadas Coahuila",
        'cat': 1,
        'periodicos': objs
    }

    return render(request, 'portadas-y-columnas.html', context)


def portada(request, slug):
    queryset = PortadasYColumnas.objects.filter(category=1)
    obj = get_object_or_404(queryset, slug=slug)

    return render(request, 'periodico.html', {'periodico': obj})


def portadas_list_mexico(request):
    objs = PortadasYColumnas.objects.filter(category=2)
    context = {
        'title': "Portadas México",
        'cat': 2,
        'periodicos': objs
    }

    return render(request, 'portadas-y-columnas.html', context)


def portada_mexico(request, slug):
    queryset = PortadasYColumnas.objects.filter(category=2)
    obj = get_object_or_404(queryset, slug=slug)

    return render(request, 'periodico.html', {'periodico': obj})


def portadas_list_nl(request):
    objs = PortadasYColumnas.objects.filter(category=3)
    context = {
        'title': "Portadas Nuevo León",
        'cat': 3,
        'periodicos': objs
    }

    return render(request, 'portadas-y-columnas.html', context)


def portada_nl(request, slug):
    queryset = PortadasYColumnas.objects.filter(category=3)
    obj = get_object_or_404(queryset, slug=slug)

    return render(request, 'periodico.html', {'periodico': obj})

periodicos/templates/periodico.html
{% extends 'base.html' %}

{% block content %}
<section >
    <div class="container-fluid text-center px-1">
        <iframe
            src="https://drive.google.com/viewerng/viewer?url={{ periodico.file.url }}&embedded=true"
            id="pdf"
            style="height:100vh;width:100%;"
        ></iframe>
    </div>
</section>
{% endblock %}

periodicos/templates/portadas-y-columnas.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="container text-center">
          <h1>{{ title }}</h1>
        </div>
        <div class="separator"></div>
        <br />
        <div class="container">
          <div class="row">
              {% for periodico in periodicos %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
                {% if cat == 1 %}
                    <a href="{% url 'periodicos:portada' periodico.slug %}">
                {% elif cat == 2 %}
                    <a href="{% url 'periodicos:portada_mexico' periodico.slug %}">
                {% elif cat == 3 %}
                    <a href="{% url 'periodicos:portada_nl' periodico.slug %}">
                {% endif %}
                    <img
                      class="img-fluid"
                      src="{{ periodico.thumbnail.url }}"
                      alt=""
                    />
                  </a>
                </div>
              {% endfor %}
          </div>
        </div>
    </section>
{% endblock %}